### ISSUE TITLE
Dead reference to createTask?

### ISSUE THREAD

**Issue by Anahkiasen** [hichroma/learnstorybook-code#1]
Following the guide currently, arrived at [this page](https://www.learnstorybook.com/composite-component/) and I noticed a paragraph referencing code which I think changed since:

> createTask() is a helper function that generates shape of a Task that we created and exported from the Task.stories.js file. Similarly, actions exported from Task.stories.js defined the actions (mocked callbacks) that a Task component expects, which the TaskList also needs.

Couldn't find any reference to a `createTask` so I'm assuming this was changed after this was written

**Comment by domyen** [comment]
Bingo! We just merged a PR that refactored how this was done. I'll make the necessary edits.
